url: 'https://wearegodigital.github.io'
baseurl: 'bronson-static'
# bronson-static
title: 'Bronson Farr'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

sass:
load_paths:
  - _sass
  - node_modules

include: ["node_modules/tailwindcss"]
